services:
  - type: web
    name: telegram-docker-deploy-manager
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BASE_URL
        sync: false
      - key: MONGODB_URL
        sync: false
