services:
  - type: web
    name: telegram-file-sequencer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ADMINS
        sync: false
      - key: PORT
        sync: false
      - key: REPLACE_TEXT_CHANNELS
        sync: false
