services:
  - type: web
    name: render-deployer-bot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: ENCRYPTION_SECRET
        generateValue: true
